title: Leites Naturais
author: GitHub mlumoura
email: mlumoura@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Esse blog irá conter dicas e receitas de leites naturais para quem não pode consumir leite de origem animal e tmabém para aqueles que desejam ter uma vida mais saudável.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme:minima
